# Generated by Django 3.2.15 on 2022-10-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='scu',
            new_name='sku',
        ),
    ]
